image: debian:stretch

cache:
  key: global
  paths:
    - t-gen/
    - .cache

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - mkdir -p .cache/apt && printf 'Dir::Cache::Archives "%s";\n' "$(pwd)/.cache/apt" > /etc/apt/apt.conf.d/local-cachedir
  - printf '%s\n' 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install -y ffmpeg normalize-audio jq
  - apt-get install -y git
  - apt-get install -y sqlite3
  - apt-get install -y -t stretch-backports git-lfs
  - apt-get install -y perl libconfig-general-perl libdbi-perl libdbd-sqlite3-perl libfile-slurp-perl libfile-slurper-perl libipc-run3-perl liblist-moreutils-perl libscalar-list-utils-perl liblog-log4perl-perl libwww-perl libmp3-info-perl libnumber-format-perl libogg-vorbis-header-pureperl-perl libterm-size-any-perl libtext-asciitable-perl libtext-csv-perl liburi-perl libxml-feedpp-perl libdata-dump-perl libtest-exception-perl libmoose-perl libipc-run-perl libjson-maybexs-perl libnamespace-autoclean-perl libclone-perl libhash-merge-perl libtest-deep-perl libuuid-perl libtap-harness-archive-perl libdatetime-perl libfile-pushd-perl
  - apt-get install -y festival festvox-kallpc16k sox libsox-fmt-mp3
  - mkdir -p .cache/lfs && git config --global --add 'lfs.storage' "$(pwd)/.cache/lfs"
  - git-lfs install
  - git submodule init
  - git submodule update

# try not to accumulate ancient packages
after_script:
  - apt-get autoclean

test_prove:
  stage: test
  script:
    - mkdir -p artifacts/tap
    - t/make-test-feeds 
    - LIVE_DANGEROUSLY=1 prove -a artifacts/tap/
  artifacts:
    paths: 
      - artifacts
    expire_in: 1 month
    when: always
