before_script:
  - ./ci/setup-root.sh
  - ./ci/setup-user.sh

# try not to accumulate ancient packages
after_script:
  - apt-get autoclean

.common-script: &common-script
  - if [ "$PODIST_CI_DO_COVERAGE" = "y" ]; then echo 'Doing coverage'; cover -delete; export HARNESS_PERL_SWITCHES='-MDevel::Cover=+ignore,^t\\/,+ignore,^\\/usr\\/'; fi
  - PODIST_CI_PARALLEL=$( [ $(nproc) -gt 1 ] && echo 3 || echo 1)
  - printf 'Running with prove -j%d\n' $PODIST_CI_PARALLEL
  - LIVE_DANGEROUSLY=1 prove -a artifacts/tap/ -j$PODIST_CI_PARALLEL t/system-testing/basic-usage.t t/
  - if [ "$PODIST_CI_DO_COVERAGE" = "y" ]; then cover -report html_basic -output artifacts/cover_html; fi


test_stretch:
  cache:
    key: stretch
    paths:
      - t-gen/
      - .cache
  image: debian:stretch
  stage: test
  variables:
    PODIST_CI_DO_COVERAGE: 'y'
  script: *common-script
  artifacts:
    paths:
      - artifacts
    expire_in: 1 month
    when: always

test_buster:
  only:
    - master
    - merge_requests
    - web
  cache:
    key: buster
    paths:
      - t-gen/
      - .cache
  image: debian:buster
  stage: test
  variables:
    PODIST_CI_DO_COVERAGE: 'n'
  script: *common-script
  artifacts:
    paths:
      - artifacts
    expire_in: 1 month
    when: always

test_bullseye:
  only:
    - master
    - merge_requests
    - web
  cache:
    key: bullseye
    paths:
      - t-gen/
      - .cache
  image: debian:bullseye
  stage: test
  variables:
    PODIST_CI_DO_COVERAGE: 'n'
  script: *common-script
  artifacts:
    paths:
      - artifacts
    expire_in: 1 month
    when: always

pages:
  image: debian:stretch
  only:
    - master
  stage: deploy
  dependencies:
    - test_stretch
  before_script: []
  script:
    - mkdir public
    - cp -R artifacts/cover_html public/coverage
  after_script: []
  artifacts:
    paths:
      - public/
